armas:
  cuchillo:
    da単o_min: 15
    da単o_max: 25
    rango: 1.0
    precio: 0
    
  glock:
    da単o_base: 30
    precision: 0.85
    distancia_efectiva: 10.0
    precio: 300
    balas_por_cargador: 15
    tiempo_recarga: 2.0
    
  ak47:
    da単o_base: 25
    precision: 0.75
    distancia_efectiva: 15.0
    precio: 2700
    balas_por_cargador: 30
    tiempo_recarga: 2.5
    rafaga: 3
    retardo_rafaga: 0.4