# -- Server Configuration --

server:
  port: 1500

player:
  health: 100
  money: 500

weapons:
  knife:
    price: 0
    range: 45
    min_damage: 10
    max_damage: 20
    precision: 1

  glock:
    price: 0
    range: 100
    min_damage: 10
    max_damage: 20
    precision: 0.8

  bomb:
    price: 0
    range: 0
    min_damage: 500
    max_damage: 500
    precision: 1

  ak47:
    price: 100
    range: 150
    min_damage: 20
    max_damage: 30
    precision: 0.8

  m3:
    price: 200
    range: 125
    min_damage: 15
    max_damage: 25
    precision: 0.9

  awp:
    price: 300
    range: 200
    min_damage: 30
    max_damage: 40
    precision: 0.95

rounds:
  total: 10
  terrorists: 1
  counterterrorists: 2

# -- Client Configuration --