# -- Server Configuration --

server:
  port: 1500

player:
  health: 100
  money: 500

weapons:
  knife:
    price: 0
    range: 45
    min_damage: 10
    max_damage: 20
    precision: 1
    cooldown: 0.0

  glock:
    price: 0
    range: 150
    min_damage: 20
    max_damage: 30
    precision: 0.8
    cooldown: 0.1

  bomb:
    price: 0
    range: 0
    min_damage: 500
    max_damage: 500
    precision: 1
    cooldown: 0.0

  ak47:
    price: 270
    range: 150
    min_damage: 15
    max_damage: 25
    precision: 0.8
    cooldown: 0.2

  m3:
    price: 200
    range: 100
    min_damage: 25
    max_damage: 35
    precision: 0.9
    cooldown: 0.8

  awp:
    price: 500
    range: 200
    min_damage: 40
    max_damage: 50
    precision: 0.95
    cooldown: 1.5

rounds:
  total: 10

# -- Client Configuration --